In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
pd.read_csv("Data Analyst .csv")

,Call Id,Lead Id,Campaign ID,Advertiser Id,Hid,Call Status,Lead Status,Agent Duration(seconds),Customer Duration(seconds),From Calling Number,To Calling Number,Attempt No,Created At,Updated At,Agent Id,Agent Name
0,26807,410987,930228,1883,40831aceu6850re1ece43deeqf20a6o,no-answer,Not Interested,8,0,9.186570e+11,+919552777764,1,2024-04-01 11:35:19,2024-04-01 11:35:27,2728,Mansi Jaiswal
1,26808,410986,930228,1883,3dc489fbg6850pe1ece43deewf20a6v,completed,Not Interested,51,34,9.186570e+11,+917275507242,1,2024-04-01 11:35:27,2024-04-01 11:36:19,2728,Mansi Jaiswal
2,26809,410985,930228,1883,92d7bfbag6850se1ece43deevf20a6y,no-answer,Invalid Number,9,0,9.186570e+11,+919430734094,1,2024-04-01 11:36:19,2024-04-01 11:36:28,2728,Mansi Jaiswal
3,26810,410984,930228,1883,3a9872eem6850oe1ece43deetf20a6m,completed,Not Interested,45,25,9.186570e+11,+918349289209,1,2024-04-01 11:36:29,2024-04-01 11:37:15,2728,Mansi Jaiswal
4,26811,410981,930228,1883,3dde873bx6850je1ece43deehf20a6u,no-answer,Busy,45,0,9.186570e+11,+917054670061,1,2024-04-01 11:37:14,2024-04-01 11:38:00,2728,Mansi Jaiswal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24618,51694,452649,930270,1883,d449d4aewcze1ec687663hcne4373a65,completed,Not Interested,30,21,9.186570e+11,7837713409,1,2024-05-15 19:18:00,2024-05-15 19:18:31,2804,Niharika Bhatt
24619,51695,452648,930270,1883,43d96decjcle1ec687663zcnf55dce0f,completed,Call Back,34,23,9.186570e+11,9915515529,1,2024-05-15 19:18:30,2024-05-15 19:19:09,2804,Niharika Bhatt
24620,51696,452647,930270,1883,ff5897edxcwe1ec687663zcva2756b59,completed,Not Interested,79,60,9.186570e+11,9166733250,1,2024-05-15 19:19:09,2024-05-15 19:20:29,2804,Niharika Bhatt
24621,51697,452646,930270,1883,b485f83fjcle1ec687663kcy54cfacf3,no-answer,Voice Issue,16,0,9.186570e+11,9888255000,1,2024-05-15 19:20:28,2024-05-15 19:20:45,2804,Niharika Bhatt
24622,51698,452646,930270,1883,b485f83fjcle1ec687663kcy54cfacf3,completed,Voice Issue,51,35,9.186570e+11,9888255000,2,2024-05-15 19:20:45,2024-05-15 19:21:36,2804,Niharika Bhatt

In [6]:
df = pd.read_csv("Data Analyst .csv")

In [7]:
df

,Call Id,Lead Id,Campaign ID,Advertiser Id,Hid,Call Status,Lead Status,Agent Duration(seconds),Customer Duration(seconds),From Calling Number,To Calling Number,Attempt No,Created At,Updated At,Agent Id,Agent Name
0,26807,410987,930228,1883,40831aceu6850re1ece43deeqf20a6o,no-answer,Not Interested,8,0,9.186570e+11,+919552777764,1,2024-04-01 11:35:19,2024-04-01 11:35:27,2728,Mansi Jaiswal
1,26808,410986,930228,1883,3dc489fbg6850pe1ece43deewf20a6v,completed,Not Interested,51,34,9.186570e+11,+917275507242,1,2024-04-01 11:35:27,2024-04-01 11:36:19,2728,Mansi Jaiswal
2,26809,410985,930228,1883,92d7bfbag6850se1ece43deevf20a6y,no-answer,Invalid Number,9,0,9.186570e+11,+919430734094,1,2024-04-01 11:36:19,2024-04-01 11:36:28,2728,Mansi Jaiswal
3,26810,410984,930228,1883,3a9872eem6850oe1ece43deetf20a6m,completed,Not Interested,45,25,9.186570e+11,+918349289209,1,2024-04-01 11:36:29,2024-04-01 11:37:15,2728,Mansi Jaiswal
4,26811,410981,930228,1883,3dde873bx6850je1ece43deehf20a6u,no-answer,Busy,45,0,9.186570e+11,+917054670061,1,2024-04-01 11:37:14,2024-04-01 11:38:00,2728,Mansi Jaiswal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24618,51694,452649,930270,1883,d449d4aewcze1ec687663hcne4373a65,completed,Not Interested,30,21,9.186570e+11,7837713409,1,2024-05-15 19:18:00,2024-05-15 19:18:31,2804,Niharika Bhatt
24619,51695,452648,930270,1883,43d96decjcle1ec687663zcnf55dce0f,completed,Call Back,34,23,9.186570e+11,9915515529,1,2024-05-15 19:18:30,2024-05-15 19:19:09,2804,Niharika Bhatt
24620,51696,452647,930270,1883,ff5897edxcwe1ec687663zcva2756b59,completed,Not Interested,79,60,9.186570e+11,9166733250,1,2024-05-15 19:19:09,2024-05-15 19:20:29,2804,Niharika Bhatt
24621,51697,452646,930270,1883,b485f83fjcle1ec687663kcy54cfacf3,no-answer,Voice Issue,16,0,9.186570e+11,9888255000,1,2024-05-15 19:20:28,2024-05-15 19:20:45,2804,Niharika Bhatt
24622,51698,452646,930270,1883,b485f83fjcle1ec687663kcy54cfacf3,completed,Voice Issue,51,35,9.186570e+11,9888255000,2,2024-05-15 19:20:45,2024-05-15 19:21:36,2804,Niharika Bhatt

In [8]:
df.describe()

,Call Id,Lead Id,Campaign ID,Advertiser Id,Agent Duration(seconds),Customer Duration(seconds),From Calling Number,Attempt No,Agent Id
count,24623.000000,24623.000000,24623.000000,24623.000000,24623.000000,24623.000000,2.450000e+04,24623.000000,24623.000000
mean,39308.926898,432166.407018,930255.478252,1882.260529,35.938432,12.986679,9.186570e+11,2.880721,2764.284449
std,7178.280657,14006.878960,17.759824,43.326309,26.882256,25.441664,3.021055e+00,1.901573,80.442590
min,26807.000000,342820.000000,930056.000000,367.000000,0.000000,0.000000,9.186570e+11,1.000000,1.000000
25%,33106.500000,425459.000000,930247.000000,1883.000000,17.000000,0.000000,9.186570e+11,1.000000,2728.000000
50%,39302.000000,438267.000000,930264.000000,1883.000000,33.000000,0.000000,9.186570e+11,2.000000,2772.000000
75%,45524.500000,440860.000000,930268.000000,1883.000000,48.000000,18.000000,9.186570e+11,4.000000,2791.000000
max,51698.000000,454079.000000,930270.000000,1889.000000,495.000000,476.000000,9.186570e+11,11.000000,2804.000000

In [9]:
df.dtypes

Call Id                         int64
Lead Id                         int64
Campaign ID                     int64
Advertiser Id                   int64
Hid                            object
Call Status                    object
Lead Status                    object
Agent Duration(seconds)         int64
Customer Duration(seconds)      int64
From Calling Number           float64
To Calling Number              object
Attempt No                      int64
Created At                     object
Updated At                     object
Agent Id                        int64
Agent Name                     object
dtype: object

In [21]:
# Total calls (count of call_sid)
total_calls = len(df)

# Display the result
print("Total calls:", total_calls)

Total calls: 24623

In [45]:
df

,Call Id,Lead Id,Campaign ID,Advertiser Id,Hid,Call Status,Lead Status,Agent Duration(seconds),Customer Duration(seconds),From Calling Number,To Calling Number,Attempt No,Created At,Updated At,Agent Id,Agent Name
0,26807,410987,930228,1883,40831aceu6850re1ece43deeqf20a6o,no-answer,Not Interested,8,0,9.186570e+11,+919552777764,1,2024-04-01 11:35:19,2024-04-01 11:35:27,2728,Mansi Jaiswal
1,26808,410986,930228,1883,3dc489fbg6850pe1ece43deewf20a6v,completed,Not Interested,51,34,9.186570e+11,+917275507242,1,2024-04-01 11:35:27,2024-04-01 11:36:19,2728,Mansi Jaiswal
2,26809,410985,930228,1883,92d7bfbag6850se1ece43deevf20a6y,no-answer,Invalid Number,9,0,9.186570e+11,+919430734094,1,2024-04-01 11:36:19,2024-04-01 11:36:28,2728,Mansi Jaiswal
3,26810,410984,930228,1883,3a9872eem6850oe1ece43deetf20a6m,completed,Not Interested,45,25,9.186570e+11,+918349289209,1,2024-04-01 11:36:29,2024-04-01 11:37:15,2728,Mansi Jaiswal
4,26811,410981,930228,1883,3dde873bx6850je1ece43deehf20a6u,no-answer,Busy,45,0,9.186570e+11,+917054670061,1,2024-04-01 11:37:14,2024-04-01 11:38:00,2728,Mansi Jaiswal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24618,51694,452649,930270,1883,d449d4aewcze1ec687663hcne4373a65,completed,Not Interested,30,21,9.186570e+11,7837713409,1,2024-05-15 19:18:00,2024-05-15 19:18:31,2804,Niharika Bhatt
24619,51695,452648,930270,1883,43d96decjcle1ec687663zcnf55dce0f,completed,Call Back,34,23,9.186570e+11,9915515529,1,2024-05-15 19:18:30,2024-05-15 19:19:09,2804,Niharika Bhatt
24620,51696,452647,930270,1883,ff5897edxcwe1ec687663zcva2756b59,completed,Not Interested,79,60,9.186570e+11,9166733250,1,2024-05-15 19:19:09,2024-05-15 19:20:29,2804,Niharika Bhatt
24621,51697,452646,930270,1883,b485f83fjcle1ec687663kcy54cfacf3,no-answer,Voice Issue,16,0,9.186570e+11,9888255000,1,2024-05-15 19:20:28,2024-05-15 19:20:45,2804,Niharika Bhatt
24622,51698,452646,930270,1883,b485f83fjcle1ec687663kcy54cfacf3,completed,Voice Issue,51,35,9.186570e+11,9888255000,2,2024-05-15 19:20:45,2024-05-15 19:21:36,2804,Niharika Bhatt

In [25]:
df.shape

(24623, 16)

In [26]:
df.index

RangeIndex(start=0, stop=24623, step=1)

In [29]:
df.dropna(inplace=True)  # Drop rows with missing values

In [30]:
df.drop_duplicates(inplace=True)

In [37]:
df.head(2)

,Call Id,Lead Id,Campaign ID,Advertiser Id,Hid,Call Status,Lead Status,Agent Duration(seconds),Customer Duration(seconds),From Calling Number,To Calling Number,Attempt No,Created At,Updated At,Agent Id,Agent Name
0,26807,410987,930228,1883,40831aceu6850re1ece43deeqf20a6o,no-answer,Not Interested,8,0,9.186570e+11,+919552777764,1,2024-04-01 11:35:19,2024-04-01 11:35:27,2728,Mansi Jaiswal
1,26808,410986,930228,1883,3dc489fbg6850pe1ece43deewf20a6v,completed,Not Interested,51,34,9.186570e+11,+917275507242,1,2024-04-01 11:35:27,2024-04-01 11:36:19,2728,Mansi Jaiswal

In [11]:
df['Call Status'].value_counts().sum()

24623

In [12]:
df['Lead Id'].nunique()

8278

In [24]:
df['Lead Id'].unique() #Answer

array([410987, 410986, 410985, ..., 452648, 452647, 452646])

In [30]:
df['Lead Id'].value_counts().sum()

24623

In [44]:


# Count the number of calls with call_status "Answered"
connected_calls = df[df["Call Status"] == "Answered"].shape[0]

print("Number of connected calls:", connected_calls)

Number of connected calls: 0

In [49]:
# Filter the DataFrame to include only rows where call_status is "Answered"
answered_calls_df = df[df['Call Status'] == "Answered"]

# Count the number of unique lead IDs
unique_connected_calls = answered_calls_df['Lead Id'].nunique()

print("Unique calls connected:", unique_connected_calls)

Unique calls connected: 0

In [51]:
# Count the number of calls with call_status "Interested"
converted_leads = df[df['Call Status'] == "Interested"].shape[0]

print("Number of converted leads:", converted_leads)

Number of converted leads: 0

In [52]:
# Define criteria for qualified leads
criteria = (df['Call Status'] == "Interested") & (df['demographic_criteria'] == "met")

# Filter the DataFrame based on criteria
qualified_leads_df = df[criteria]

# Count the number of qualified leads
qualified_leads_count = qualified_leads_df.shape[0]

print("Qualified leads:", qualified_leads_count)

KeyError: 'demographic_criteria'

In [53]:
# Count the number of calls with call_status "Not Interested"
lost_leads = df[df['Call Status'] == "Not Interested"].shape[0]

print("Number of lost leads:", lost_leads)

Number of lost leads: 0

In [68]:
#Calculate the average Agent Call Duration
average_agent_call_duration = df['Agent Call Duration'].mean()

print("Average agent call duration:", average_agent_call_duration)

KeyError: 'Agent Call Duration'

In [69]:
# Calculate the average customer call duration
average_customer_call_duration = df['Customer Call Duration'].mean()

print("Average customer call duration:", average_customer_call_duration)

KeyError: 'Customer Call Duration'